### PR TITLE
Issue56 - added a unit tests and changed NorthwindModels.Customer

### PR DESCRIPTION
**Pull request by kaumasse**
Hey Tony,

I've added 2 test for Issue56 https://github.com/tonysneed/trackable-entities/issues/56. The first will succeed the second will fail. Couldn't find the problem, at the first sight, your code is complex. Please, rename the methods. You're right we need some more tests for GetChanges, tests for ApplyChanges are pretty good so far.

Mathias

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks for this PR ... I've been tied up the past few days, but I'll be sure to have a look at the PR this week.  Appreciate your patience. :cold_sweat:

**Comment by kaumasse** [comment]
Hey Tony, no problem, how you can manage it! I'll make some more tests in the next weeks. Best regards. Mathias

**Comment by tonysneed** [comment]
Terrific, I'm going to fix the GetChanes issue this morning. I also had to fix the WCF template for the TE installer, so I'll include v2.5.2 in a new installer. Also working on a new set of docs and how-to videos.

**Comment by tonysneed** [comment]
This has been resolved by PR #65.

**Pull request closed without merging**
